## Confidence Interval Questions

In [1]:
import numpy as np
import seaborn as sns
from scipy import stats
from math import sqrt
import warnings
warnings.filterwarnings("ignore")

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [8]:
stats.norm.ppf([0.025, 0.975])

array([-1.95996398,  1.95996398])

-1.9599639845400545

In [15]:
stats.t.ppf([0.025,0.975],1199)

array([-1.96194449,  1.96194449])

#### Q1. A Tire manufacturer wants to estimate the average number of miles that may be driven on a tire of a certain type before the tire wears out. A random sample of 32 tires is chosen, the tires are driven on until they wear out, and the number of miles driven on each tire is recorded. The data in thousands of miles, are as follows:
32, 33, 28, 37,29,30,25,27,39,40,26,26,27,30,25,30,31,29,24,36,25,37,37,20,22,35,23,28,30,36,40,41
Give a 90%,95%, 99% CI for the average number of miles that may be driven on a tire of this kind.

In [14]:
data1 = [32, 33, 28, 37, 29, 30, 25, 27, 39, 40, 26, 26, 27, 30, 25, 30, 31, 29, 24, 36, 25, 37, 37, 20, 22, 
         35, 23, 28, 30, 36, 40, 41]
x_bar1 = np.mean(data1)
s1 = np.std(data1, ddof=1) ## Sample Standard Deviation
n1 = len(data1)
df1 = n1-1
print(n1)
print(df1)

##90% CI
T_90_CI = stats.t.ppf([0.05,0.95],df1)
print(T_90_CI)
print("90%")
x_bar1 + T_90_CI*s1/sqrt(n1)


T_95_CI = stats.t.ppf([0.025,0.975],df1)
print(T_95_CI)
print("95%")
x_bar1 + T_95_CI*s1/sqrt(n1)

T_99_CI = stats.t.ppf([0.005,0.995],df1)
print(T_99_CI)
print("99%")
x_bar1 + T_99_CI*s1/sqrt(n1)

32
31
[-1.69551879  1.69551879]
90%


array([28.83156489, 32.29343511])

[-2.03951345  2.03951345]
95%


array([28.4803848, 32.6446152])

[-2.74404192  2.74404192]
99%


array([27.76114, 33.36386])

#### Q2. An article in USA today discusses things Americans do to try to rid themselves of junk e-mail. If a random sample of 1200 internet users yields an average of 43 junk e-mails messages per day and standard deviation is 14. Give 99% confidence interval

In [3]:
x_bar2 = 43
s2 = 14
n2 = 1200
df2 = n2-1

In [4]:
##90% CI
T_90_CI = stats.t.ppf([0.05,0.95],df2)
x_bar2 + T_90_CI*s2/sqrt(n2)

T_95_CI = stats.t.ppf([0.025,0.995],df2)
x_bar2 + T_95_CI*s2/sqrt(n2)

T_99_CI = stats.t.ppf([0.005,0.995],df2)
x_bar2 + T_99_CI*s2/sqrt(n2)

array([42.33472631, 43.66527369])

array([42.20708957, 44.04266872])

array([41.95733128, 44.04266872])

In [5]:
N_90_CI = stats.norm.ppf([0.05,0.95])
x_bar2 + N_90_CI*s2/sqrt(n2)

N_95_CI = stats.norm.ppf([0.025,0.995])
x_bar2 + N_95_CI*s2/sqrt(n2)

N_99_CI = stats.norm.ppf([0.005,0.995])
x_bar2 + N_99_CI*s2/sqrt(n2)

array([42.33524032, 43.66475968])

array([42.20788999, 44.04100902])

array([41.95899098, 44.04100902])

#### Q3. The makers of a medicated facial skin cream are interested in determining the percentage of people in a given age group who may benefit from the ointment. A random sample of 68 people results in 42 successful treatments. Give 90%, 95%, 99% CI for the proportion of people in the given age group who may be successfully treated with facial cream.

In [6]:
##Q3 Propporytion related 
p = 42/68
q = 1-p
s3 = sqrt(p*q)
n3 = 68
#n*p and n*q > 5

N_90_CI = stats.norm.ppf([0.05,0.95])
p + N_90_CI*s3/sqrt(n3)

N_95_CI = stats.norm.ppf([0.025,0.975])
p + N_95_CI*s3/sqrt(n3)

N_99_CI = stats.norm.ppf([0.005,0.995])
p + N_99_CI*s3/sqrt(n3)

array([0.52071327, 0.71458085])

array([0.50214332, 0.7331508 ])

array([0.46584942, 0.7694447 ])

#### Q4 A company that conducts survey of current jobs for executives want to estimate the average salary of an executive at a given level to within \$2000 with 95% CI. From previous surveys it is known that variance of executive salaries is 40,000,000. What is the minimum required sample ?

In [25]:
B = 3000
v4 = 40000000
zalpha = stats.norm.ppf([0.95,0.975, 0.995])
n4 = (zalpha**2*v4 )/B**2

In [26]:
n4

array([12.02463757, 17.07315031, 29.48842934])

#### Q5 Find the minimum required sample size of accounts if the proportion of accounts in error is to be estimated to be within 0.02 with 95% confidence. A rough guess of the proportion of accounts in error is 0.10.

In [9]:
p = 0.1
q = 1-p
B5 = 0.02
n5 = (zalpha**2* p*q)/B5**2
n5

array([ 608.74727717,  864.32823466, 1492.85173523])