# Hypothesis Testing

In [3]:
import numpy as np
from scipy import stats
from math import sqrt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

#### 1.	A certain prescription medicine is supposed to contain an average of 247 parts per million(ppm) of a certain chemical. If the concentration is higher than 247 ppm, the drug may cause some side effects., and if the concentration is below 247 ppm the drug may be ineffective. The manufacturer wants to check whether the averge concentration in a large shipment is the required 247 ppm or not. A random sample of 60 portions is tested, and the sample mean is found to be 250 ppm and sample standard deviation is 12ppm. Formulate the hypothesis and test it different alphas = 0.05 and 0.01. State your conclusion

In [2]:
xbar1 = 250
s1 = 12
n1 = 60

mu0 = 247

## Option 1
t_test_statistic1 = (xbar1 - mu0) / (s1/sqrt(n1))
stats.t.sf(t_test_statistic1,df = n1-1)
2*stats.t.sf(t_test_statistic1,df = n1-1)

0.02880084884303063

0.05760169768606126

In [3]:
xbar1 = 250
s1 = 12
n1 = 60

mu0 = 247

## Option 1
z_test_statistic1 = (xbar1 - mu0) / (s1/sqrt(n1))
stats.norm.sf(z_test_statistic1)
2*stats.norm.sf(z_test_statistic1)

0.026403755708056816

0.05280751141611363

In [3]:
## Option2
t_test_statistic1
stats.t.ppf((0.05, 0.95), df = n1-1)
stats.t.ppf((0.025, 0.975), df = n1-1)
stats.t.ppf((0.005, 0.995), df = n1-1)

1.9364916731037083

array([-1.67109303,  1.67109303])

array([-2.00099538,  2.00099538])

array([-2.66175875,  2.66175875])

#### 2.	Out of all air-travel bookings in major airlines, at least 58% are said to be done online. A sample of 70 airlines revealed 52% of bookings for last year were done online. State the null and alternate Hypothesis and test it 5% level of significance 

In [4]:
n2 = 70
p2 = 0.52
q2 = 1-p2
po = 0.58

z_test_statistic_2 = (p2-po) / sqrt(po * (1-po)/n2)
stats.norm.sf(z_test_statistic_2)

0.8454459414264345

In [5]:
z_test_statistic_2
stats.norm.ppf(0.95)
stats.norm.ppf(0.975)
stats.norm.ppf(0.995)

-1.0170952554312147

1.6448536269514722

1.959963984540054

2.5758293035489004

#### 3.	 A market researcher study is undertaken to test which of the two popular electric shavers , a model of Norelco or model made by Remington, is preferred by consumers. A random sample of 25 men who regularly use an electric shaver, but not one of the two models to be tested, is chosen.
Each man is then asked to shave one morning with Norelco and the next morning with Remington or vice versa. The order, which model is used on which day is randomly chosen for each man, 
After every shave, each man is asked to complete a questionnaire rating his satisfaction with the shaver. From a questionnaire, a total satisfaction score on a scale of 0 to 100 is computed. Then, for each man the difference between the satisfaction score for Norelco and that for Remington is computed. The score differences are 
15, -8 , 32, 57, 20 , 10, -18, -12, 60, 72, 38, -5, 16, 22, 34, 41, 12, -38, 16, -40, 75,11, 2, 44, 10
Which model if any, is statistically preferred over the other ? How confident are you on your findings?


In [6]:
sample_diff = [15, -8 , 32, 57, 20 , 10, -18, -12, 60, 72, 38, -5, 16, 22, 34, 41, 12, -38, 16, -40, 75,11, 2, 44, 10]
mu_diff = 0 
n = len(sample_diff)
x_bar_diff = np.mean(sample_diff)
s = np.std(sample_diff)
T_value = (x_bar_diff - mu_diff) / (s/sqrt(n))

stats.t.ppf((0.05,0.95),n-1)
stats.t.ppf((0.025,0.975),n-1)
stats.t.ppf((0.005, 0.995),n-1)

array([-1.71088208,  1.71088208])

array([-2.06389856,  2.06389856])

array([-2.7969395,  2.7969395])

In [7]:
stats.t.sf(T_value, n-1)

0.0021738610085629074

#### 4.	LINC is a software tool developed by Burroughs Corporation. The program automatically writes some of the coding that programmers have to do manually. LINC supposedly saves programming time and allows programme to operate more efficiently. In a test of the software package, 45 programmers (group1) were asked to write a program without LINC and run the program until it performed with no bugs. The times from start to finish for this group were recorded. Group 2 consists of 32 programmers who were asked to prepare the same program with aid of LINC. Before getting the data, the protocol established was to run the test as a one-tailed test to prove that package reduces the average programming time. The results were x1_bar = 26, x2_bar = 21 (in minutes), s1 = 8, s2 = 6 (in minutes). Conduct the test and state your conclusion. Is LINC effective in reducing the average  programming time ??


In [4]:
x1_bar = 26
x2_bar = 21
s1 = 8 
s2 = 6 
n1 = 45
n2 = 32

df = n1+n2-2
mu_diff3 = 0 

#pooled standard deviation 
sp = sqrt(((n1-1) * s1**2 + (n2-1) * s2**2 )/(n1+n2-2))

print(sp)

7.240626123938915


In [6]:
t_value3 = ((x1_bar -x2_bar ) - mu_diff3)/(sp *sqrt(1/n1+1/n2))
stats.t.sf(t_value3, df)
stats.t.sf(t_value3, n1+n2-2)


0.0019064940012790757

0.0019064940012790757

In [7]:
t_value3
stats.t.ppf(0.95, df )
stats.t.ppf(0.975, df )
stats.t.ppf(0.995, df )

2.9862747688635984

1.6654253732396658

1.9921021536898653

2.642983063369744